spring:
  application:
    name: aurasage-document-service

  data:
    mongodb:
        uri: mongodb://root:devpassword@localhost:27018/aurasage?authSource=admin
    # dynamodb:
    #     endpoint: http://localhost:8000
    #     region: us-west-2

aurasage:
  database:
    type: mongodb # dynamodb (default mongodb)
  observability:
    enabled: true # Set to false to disable all observability features
    stack: local # Options: local, aws


# OpenAPI & Swagger
# Access the Swagger UI at http://localhost:8080/swagger-ui.html
springdoc:
    api-docs:
      path: /v1/api-docs
      enabled: true
    swagger-ui:
      enabled: true

management:
  tracing:
    enabled: true
    propagation:
      type:
      - W3C
    baggage:
      enabled: true
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
#   zipkin:
#     tracing:
#       endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,httptrace
  metrics:
    tags:
      application: ${spring.application.name}