spring:
  application:
    name: aurasage-document-service

  data:
    mongodb:
        uri: mongodb://root:devpassword@localhost:27018/aurasage?authSource=admin
    # dynamodb:
    #     endpoint: http://localhost:8000
    #     region: us-west-2

aurasage:
  database:
    type: mongodb # dynamodb (default mongodb)
  observability:
    enabled: true # Set to false to disable all observability features
    stack: opensource # Options: opensource, aws


# OpenAPI & Swagger
# Access the Swagger UI at http://localhost:8080/swagger-ui.html
springdoc:
    api-docs:
      path: /v1/api-docs
      enabled: true
    swagger-ui:
      enabled: true